---
title: '`Quiz 3` Exploratory Data Analysis'
author: "Anderson H. Uyekita"
output:
  github_document: default
  html_document:
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: true
always_allow_html: true
---

* Specialization: [Data Science: Foundations using R Specialization](https://www.coursera.org/specializations/data-science-foundations-r)
* Course: [Exploratory Data Analysis](https://www.coursera.org/learn/exploratory-data-analysis)
    * Instructor: Roger D Peng
* Week 4: 
    * Start: 2022/05/25
    * Finish: 2022/05/25

***

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache=TRUE,message=FALSE,warning=FALSE)
library(tidyverse)
library(magrittr)
```

This Quiz is part of the Getting and Cleaning Data Course.

To turn the folder more structured, I will create a subfolder to host the dataset.

```{r creating_folder,cache=TRUE}
# Checking if the subfolder already exists.
if (!dir.exists("data")) {
    
    # Creating a subfolder to store the data.
    dir.create(path = "./data")
}
```
